In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Prml/train")
(df)

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,...,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64,class
0,0.054000,0.37951,0.396410,2.04720,32.3510,0.388250,0.249760,1.330500,1.13890,0.504940,...,0.121960,0.39718,0.87804,0.001924,8.4160,5.1372,82.658,4.4158,7.42770,0
1,0.054000,0.49988,0.472250,1.94470,14.7860,0.000000,0.258340,0.996010,1.69960,0.497880,...,0.121300,0.42002,0.85300,0.000000,4.1486,3.2732,107.350,3.4000,60.98700,0
2,0.054000,0.69592,0.267130,1.55480,-1.1523,0.000000,0.309060,0.436950,1.30900,0.304080,...,0.241140,0.81774,0.76599,0.694840,4.9909,3.9510,134.270,2.7185,5.20780,0
3,0.054000,0.30734,0.458790,2.49280,51.9520,0.149880,0.092704,1.866100,1.05710,0.573530,...,0.054015,0.14207,0.94598,0.000000,4.5746,3.6147,86.435,4.2228,5.54970,0
4,0.054000,0.61323,0.229600,1.40630,-7.3128,0.187320,0.187320,0.630700,1.15590,0.386770,...,0.134850,0.48431,0.86515,0.124440,6.3985,4.3158,127.210,2.8692,7.89800,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29842,-0.076836,0.51194,0.196600,1.38590,-133.3800,-0.076836,-0.074938,-0.245900,1.03000,-0.125890,...,0.029134,0.61036,0.97087,-0.020175,1.9645,21.3700,155.100,2.3534,4.07770,1
29843,-0.283380,0.97794,-0.125140,0.64902,-56.1260,-1.329800,-0.283380,0.022514,1.39430,0.022018,...,0.032555,-12.87100,0.97208,24.893000,9.8129,16.6910,93.338,3.9105,1.81430,1
29844,-0.578050,0.96702,-0.800850,0.16576,-67.3650,-0.578050,-0.578050,-0.403340,0.93979,-0.390040,...,-0.064073,1.48200,1.06410,-0.018084,110.7200,44.7590,81.220,4.4940,5.13050,1
29845,-0.179050,1.25530,-0.275990,0.74554,-120.4400,-0.179050,-0.154930,-0.260180,1.17490,-0.326590,...,0.148880,0.54824,0.85112,-0.522430,9.8526,3.4892,207.870,1.7559,9.95270,1
29846,-0.108860,0.74394,0.015449,1.08780,-17.0030,-0.108860,-0.109180,0.125310,0.84516,0.093224,...,-0.183200,-1.16770,1.18320,6.092400,13.8860,6.0769,83.122,4.3911,0.95575,1

In [ ]:
df.isnull().sum().sum()

0

In [ ]:
df_x = df.drop(columns="class")
df_x

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,...,Attr55,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64
0,0.054000,0.37951,0.396410,2.04720,32.3510,0.388250,0.249760,1.330500,1.13890,0.504940,...,348690.0,0.121960,0.39718,0.87804,0.001924,8.4160,5.1372,82.658,4.4158,7.42770
1,0.054000,0.49988,0.472250,1.94470,14.7860,0.000000,0.258340,0.996010,1.69960,0.497880,...,2304.6,0.121300,0.42002,0.85300,0.000000,4.1486,3.2732,107.350,3.4000,60.98700
2,0.054000,0.69592,0.267130,1.55480,-1.1523,0.000000,0.309060,0.436950,1.30900,0.304080,...,6332.7,0.241140,0.81774,0.76599,0.694840,4.9909,3.9510,134.270,2.7185,5.20780
3,0.054000,0.30734,0.458790,2.49280,51.9520,0.149880,0.092704,1.866100,1.05710,0.573530,...,20545.0,0.054015,0.14207,0.94598,0.000000,4.5746,3.6147,86.435,4.2228,5.54970
4,0.054000,0.61323,0.229600,1.40630,-7.3128,0.187320,0.187320,0.630700,1.15590,0.386770,...,3186.6,0.134850,0.48431,0.86515,0.124440,6.3985,4.3158,127.210,2.8692,7.89800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29842,-0.076836,0.51194,0.196600,1.38590,-133.3800,-0.076836,-0.074938,-0.245900,1.03000,-0.125890,...,2049.0,0.029134,0.61036,0.97087,-0.020175,1.9645,21.3700,155.100,2.3534,4.07770
29843,-0.283380,0.97794,-0.125140,0.64902,-56.1260,-1.329800,-0.283380,0.022514,1.39430,0.022018,...,-1883.0,0.032555,-12.87100,0.97208,24.893000,9.8129,16.6910,93.338,3.9105,1.81430
29844,-0.578050,0.96702,-0.800850,0.16576,-67.3650,-0.578050,-0.578050,-0.403340,0.93979,-0.390040,...,-9242.1,-0.064073,1.48200,1.06410,-0.018084,110.7200,44.7590,81.220,4.4940,5.13050
29845,-0.179050,1.25530,-0.275990,0.74554,-120.4400,-0.179050,-0.154930,-0.260180,1.17490,-0.326590,...,-58253.0,0.148880,0.54824,0.85112,-0.522430,9.8526,3.4892,207.870,1.7559,9.95270
29846,-0.108860,0.74394,0.015449,1.08780,-17.0030,-0.108860,-0.109180,0.125310,0.84516,0.093224,...,1107.5,-0.183200,-1.16770,1.18320,6.092400,13.8860,6.0769,83.122,4.3911,0.95575

In [ ]:
df_y = df["class"]
df_y

0        0
1        0
2        0
3        0
4        0
        ..
29842    1
29843    1
29844    1
29845    1
29846    1
Name: class, Length: 29847, dtype: int64

In [ ]:
import lightgbm as gbm

mod = gbm.LGBMClassifier(learning_rate=0.35)
mod.fit(df_x, df_y)

LGBMClassifier(learning_rate=0.35)

In [ ]:
test_d = pd.read_csv("/content/drive/MyDrive/Prml/test")
test_d

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,...,Attr55,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64
0,0.054000,0.64744,0.289710,1.47050,2.5349,0.000000,0.111090,0.54454,1.73480,0.35256,...,1377.10,0.605900,0.315100,0.40871,0.000000,6.3222,2.9098,129.550,2.8173,18.35200
1,0.054000,0.11148,0.119890,2.07540,-31.6430,-0.084883,-0.024300,7.67410,0.90732,0.85551,...,1366.50,-0.102140,-0.031697,1.10210,0.000000,3.6683,13.4610,76.732,4.7568,0.68991
2,0.054000,0.19885,0.081562,2.95760,90.6060,0.212650,0.078063,4.02900,1.25700,0.80115,...,15132.00,0.204440,0.084542,0.79556,0.196190,8.2122,2.7917,60.218,6.0613,0.28803
3,0.054000,0.23967,0.321240,2.47390,8.1087,0.207430,0.069715,2.54660,1.05560,0.61034,...,8200.80,0.052697,0.131070,0.94730,0.035588,6.1579,10.2190,45.422,8.0358,3.80070
4,0.054000,1.11710,-0.465770,0.46115,-152.2100,-1.175200,-0.358840,-0.11206,0.97154,-0.12518,...,-5487.20,-0.029298,2.866600,1.02930,-2.019000,8.9776,11.5070,197.430,1.8488,2.65720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12775,0.361470,0.25590,0.562760,9.75930,205.9800,-0.325970,0.516340,2.90700,0.59282,0.74391,...,2979.80,-0.155780,0.485910,0.57244,0.000000,3.3617,8.7628,39.557,9.2272,1.59020
12776,-0.084381,0.22485,0.097051,1.43160,-119.2200,-0.084381,-0.084381,2.74180,0.76553,0.61650,...,319.88,-0.306280,-0.136870,1.30630,0.000000,1.7854,8.8316,226.370,1.6124,0.53491
12777,0.059436,0.54161,0.376720,2.01920,26.6650,-0.275010,0.059436,0.84650,2.26430,0.45847,...,567.34,0.170090,0.129640,0.82727,0.375110,10.6280,4.3093,59.584,6.1258,8.93020
12778,0.012898,0.70621,0.038857,1.17220,-18.9070,0.000000,0.013981,0.41600,1.67680,0.29379,...,3599.10,0.020169,0.043904,1.01220,1.259400,13.4720,12.4320,49.117,7.4313,2.27990
12779,-0.105370,0.53629,-0.045578,0.91478,-56.0680,-0.105370,-0.109940,0.86460,0.95040,0.46367,...,-425.13,-0.052186,-0.227250,1.05220,0.003196,7.7332,4.7174,136.850,2.6672,2.79270

In [ ]:
pred = mod.predict_proba(test_d)
pred

array([[9.99999991e-01, 9.08331216e-09],
       [9.99999998e-01, 1.72431538e-09],
       [9.99999964e-01, 3.61809974e-08],
       ...,
       [8.57070696e-01, 1.42929304e-01],
       [1.76309106e-01, 8.23690894e-01],
       [5.24131463e-01, 4.75868537e-01]])

In [ ]:
pred=pred[:,1]
pred

array([9.08331216e-09, 1.72431538e-09, 3.61809974e-08, ...,
       1.42929304e-01, 8.23690894e-01, 4.75868537e-01])

In [ ]:
from google.colab import files
pred=pd.DataFrame(pred,columns=['predicted'])
pred

          predicted
0      9.083312e-09
1      1.724315e-09
2      3.618100e-08
3      2.441420e-07
4      1.411762e-06
...             ...
12775  9.999749e-01
12776  9.996658e-01
12777  1.429293e-01
12778  8.236909e-01
12779  4.758685e-01

[12780 rows x 1 columns]

In [ ]:
from sklearn.model_selection import GridSearchCV
mod2 = GridSearchCV(gbm.LGBMClassifier(learning_rate=0.35),{
    param_grid=5
},cv=5,return_train_score=False)

TypeError: ignored

In [ ]:
# pred.to_csv('rohit.csv')
# files.download('rohit.csv')

SyntaxError: ignored